x86-linux: don't include the CAN devices
The CAN devices can't be compiled under RH5 because:

net/can/can_socketcan.c:38:10: fatal error: linux/can.h: No such file or \
                                                         directory
         ^~~~~~~~~~~~~
compilation terminated.

So lets drop it as its not used anyway..

TN: RC20-027
Change-Id: I049c7e5f1175beffefc1df3055bd445f986ebdd0